### ISSUE TITLE
how can change node version always is 6.x?

### ISSUE THREAD

**Issue by suiteappdev** [tempage/dorynode#1]
how can change node version always is 6.x?

**Comment by ivere27** [comment]
https://play.google.com/store/apps/details?id=io.tempage.dorynode

upgrade node.js : 'download file' menu -> check 'appfiles' -> check 'executable'
v6.12.3 arm : https://dorynode.firebaseapp.com/v6.12.3_arm_release/node
v8.3.0 arm : https://dorynode.firebaseapp.com/v8.3.0_arm_release/node
v8.9.4 arm(only for android 5.0 above) : https://dorynode.firebaseapp.com/v8.9.4_arm_release/node
v10.15.1 arm(only for android 5.0 above) : https://dorynode.firebaseapp.com/v10.15.1_arm_release/node

**Comment by laserblue** [comment]
Checked app files and executable but protocol not found npm install npm@latest -g
