### ISSUE TITLE
Open web for some autentification

### ISSUE THREAD

**Issue by yellastronaut** [tempage/dorynode#11]
The firebase-tools has the first command to start work with it as $firebase login . And for example in termux, it's work well: it's open web page where i have to login google, after that termux get my authentification, and continue"login" procedure. 
But Dory wont do like that. Dory give me error when it should open web page. I have learn some about errors like that, but in Linux terminals, and people says it's the proxy problem. Linux terminal if it wont open web in this command, at the end open it with modification: $firebase login --no-localhost . But for Dory it's nothing.
I think it's might somehow be fixed by "intent" line in Dory settings, but i don't even imagine how exactly. Some help?

**Comment by ivere27** [comment]
I don't use the firebase tool in DoryNode but in a ubuntu server shell. 

try, copy the auth url then open it in a browser, then login.
and copy the logined url(starts with localhost:xx/...) and open it in your mobile.
