### ISSUE TITLE
NodeJS update when?

### ISSUE THREAD

**Issue by deniz-blue** [tempage/dorynode#12]
I need node v10+ because node v6 doesnt have the ... operator. I need it for a socket.io integrated project, help pls thancc oh and yeah this happens with socket.io's ws peer

**Comment by bananasmoothii** [comment]
You can download NodeJs 10 very easily as explained in the play store description. But I need NodeJs 14...

**Comment by deniz-blue** [comment]
Yeah we need Node v14 now

**Comment by ivere27** [comment]
https://github.com/tempage/dorynode/issues/17#issuecomment-790715107
