### ISSUE TITLE
"id: bad uid xxxxx" on shell

### ISSUE THREAD

**Issue by MarcoLoPinto** [tempage/dorynode#16]
Greetings,
when using the commands "whoami" or "id", the terminal returns "id: bad uid {code}".
This happens also when trying to set the password for ssh with "passwd".
I can't do much with this error.
This error does not prompt when using Termux.

Phone: LG G2 (LG-D802)
Software Version: 5.0.2

How can I solve it? Thanks.

**Comment by ivere27** [comment]
sorry for the late update.
you don't need to use 'passwd' in the shell.
there is a 'passworld' menu  in the left navigator.

be a beta tester at https://play.google.com/store/apps/details?id=io.tempage.dorynode
and reinstall dorynode.

Node v16.15.1
npm 6.14.17
arm64 (node, ssh, ssl, curl, git) / API 23
