### ISSUE TITLE
How to use NodeJs 14 ? 10 is getting really outdated...

### ISSUE THREAD

**Issue by bananasmoothii** [tempage/dorynode#17]

**Comment by ivere27** [comment]
Sorry for the late reply. (I was busy gardening :)

you are right, we need the latest version of node. 
please try this one and let me know it works or not. 
arm64/aarch64 + Android 6.0(23) required.

https://dorynode.firebaseapp.com/v14.16.0_arm64_release/node

happy coding!

**Comment by mgouget** [comment]
Hello ivere27,

Thanks for this *remarkable* piece of code! I struggled to ssh into it and so I had to dig inside  to explore the internals... before understanding that I had first to do a `whoami` in shell and then an ``ssh -l this_username ...``
```shell
`which sshd` -dddp 23456
```
 helped A LOT ;-)

Thank you for node v14.16.0 which seems to work; could it be possible also to get the corresponding npm ?

Cheers!

**Comment by therckenrath** [comment]
Hi ivere27,

I too need node 14 however I don't understand your instructions - what do I do with the file and will it work on Android 11?

Thanks,
Terry

**Comment by AirplanegoBrr** [comment]
Go inside the app press the 3 dotted lines in the top right press download file then put the link in the url box press appfiles  filename will be node make sure to mark it as executable!

[Screenshot_20211101-114134_dnodejs.jpg](https://user-images.githubusercontent.com/71111395/139723794-c978de89-e8c7-45a1-9cba-16d4745228b6.jpg)

Little late on this one sorry!

**Comment by ManuelPeh76** [comment]
To upgrade node I followed your instructions:
```
upgrade node.js :
    'download file' menu 
    -> check 'appfiles' 
    -> check 'executable'
    -> https://dorynode.firebaseapp.com/v14.16.0_arm64_release/node
```
... and when I click 'Ok' it takes about 10 secs, 
then the 'download file' window closes not saying anything.
So I went back to the terminal:
```
node --version
v6.11.4
```
Did I anything wrong??

**Comment by ManuelPeh76** [comment]
To upgrade node I followed your instructions:
```
upgrade node.js :
    'download file' menu 
    -> check 'appfiles' 
    -> check 'executable'
    -> https://dorynode.firebaseapp.com/v14.16.0_arm64_release/node
```
... and when I click 'Ok' it takes about 10 secs, 
then the 'download file' window closes not saying anything.
So I went back to the terminal:
```
node --version
v6.11.4
```
Did I anything wrong??

**Comment by CatKaster** [comment]
I had the same problem, so i went to shell, then to the bin directory:
`cd /data/user/0/io.tmpage.dorynode/files/bin`
deleted the old file:
`rm node`
downloaded the new file with cURL:
`curl -o node https://dorynode.firebaseapp.com/v14.16.0_arm64_release/node`
and at the end gave the file necessary permission:
`chmod a+x node`

**Comment by ivere27** [comment]
thanks for the instructions. :)

please try new one.
https://dorynode.firebaseapp.com/v16.15.1_arm64_release/node

let me know if not wokring.
