### ISSUE TITLE
Npm error

### ISSUE THREAD

**Issue by vsenner** [tempage/dorynode#18]
npm ERR! Linux 4.4.223-g52750b8f2138-ab6846512
npm ERR! argv "/data/user/0/io.tempage.dorynode/files/bin/node" "/data/user/0/io.tempage.dorynode/files/npm/bin/npm-cli.js" "install" "--no-bin-links"
npm ERR! node v14.16.0
npm ERR! npm  v3.10.10

npm ERR! cb.apply is not a function
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /storage/emulated/0/Work/pwa-youtube-server/npm-debug.log
code : 1 / signal : 0

**Comment by ivere27** [comment]
sorry for the late update.
be a beta tester at https://play.google.com/store/apps/details?id=io.tempage.dorynode
and reinstall dorynode.

Node v16.15.1
npm 6.14.17
arm64 (node, ssh, ssl, curl, git) / API 23

it will work.
