### ISSUE TITLE
Not able to start process on android 11

### ISSUE THREAD

**Issue by truesyssoftech** [tempage/dorynode#19]
I am using this as my web server , all thing working fine up to android 10 , but when i have created same thing on android 11 : "Samsung Galaxy Tab A" , then it is not able to start process

It always show me error "pid : 0 started"

**Comment by kevinfavaro** [comment]
I have the same issue...
In Android 11 don't start, but in Android 10 work fine.

**Comment by ivere27** [comment]
please try another node verison. 
my devices is Android 12 and v14, v16 are working well.

v6.12.3 arm : https://dorynode.firebaseapp.com/v6.12.3_arm_release/node
v8.3.0 arm : https://dorynode.firebaseapp.com/v8.3.0_arm_release/node
v8.9.4 arm(only for android 5.0 above) : https://dorynode.firebaseapp.com/v8.9.4_arm_release/node
v10.15.1 arm(only for android 5.0 above) : https://dorynode.firebaseapp.com/v10.15.1_arm_release/node
v14.16.0 arm64(only for android 6.0 above) : https://dorynode.firebaseapp.com/v14.16.0_arm64_release/node
v16.15.1 arm64(only for android 6.0 above) :  https://dorynode.firebaseapp.com/v16.15.1_arm64_release/node

**Comment by kevinfavaro** [comment]
> please try another node verison. my devices is Android 12 and v14, v16 are working well.
> 
> v6.12.3 arm : https://dorynode.firebaseapp.com/v6.12.3_arm_release/node v8.3.0 arm : https://dorynode.firebaseapp.com/v8.3.0_arm_release/node v8.9.4 arm(only for android 5.0 above) : https://dorynode.firebaseapp.com/v8.9.4_arm_release/node v10.15.1 arm(only for android 5.0 above) : https://dorynode.firebaseapp.com/v10.15.1_arm_release/node v14.16.0 arm64(only for android 6.0 above) : https://dorynode.firebaseapp.com/v14.16.0_arm64_release/node v16.15.1 arm64(only for android 6.0 above) : https://dorynode.firebaseapp.com/v16.15.1_arm64_release/node

Yes, this work fine with Android 12... but 11 don't work. After this issue, i opened the code and analyse anithing i can, and i found "the problem" (i think if this is not core of problem, but is any probllem with Android 11). For some reason, npm don't can write into mobile and don't can open port to listening. I don't have more details, because when i found it, i reportly this issue in my business and we update all Android 11 to 12.
