### ISSUE TITLE
v14.16.0_arm64 - not working 

### ISSUE THREAD

**Issue by Sergiu1-cyber** [tempage/dorynode#21]
( https://dorynode.firebaseapp.com/v14.16.0_arm64_release/node ) - not working in Xiaomi Redmi 6 

Is it possible to find a binary that would work?

( v10.15.1_arm_release ) works

**Comment by ivere27** [comment]
Hi, it seems the Xiaomi Redmi 6 is 32bit android.
you need to change the rom(32bit to 64 bit)
I don't have time to support a 32bit os. sorry.

v14.16.0_arm64 = 64bit, arm64, aarch64

ref : https://c.mi.com/thread-2477067-1-0.html
