### ISSUE TITLE
NPM ERROR

### ISSUE THREAD

**Issue by AnshB0712** [tempage/dorynode#26]
![Screenshot_2021-12-22-13-48-03-42](https://user-images.githubusercontent.com/89180266/147059367-9078af4c-7d83-456f-9448-8155abb95492.jpg)

This error is coming when i try to install express js
Anyone can help please??

**Comment by rajeshisgood** [comment]
You have to install dependencies on root directory

**Comment by ivere27** [comment]
please use '--no-bin-links' if you run npm on sdcard.

---
be a beta tester at https://play.google.com/store/apps/details?id=io.tempage.dorynode
and reinstall dorynode.

Node v16.15.1
npm 6.14.17
arm64 (node, ssh, ssl, curl, git) / API 23
