### ISSUE TITLE
Need for new nodejs (v:17)

### ISSUE THREAD

**Issue by rajeshisgood** [tempage/dorynode#27]
I need nodejs version 17 for armeabi-v7a.
Cloud you please add this . 
Or give us instructions for building my own nodejs .

**Comment by sonolosoft** [comment]
Hello, what is the latest node you have on v7a?
I only have node 10 on v7a.

I tried to use official linux node 16 arm7l and unofficial node 16 arm6l from here:
https://unofficial-builds.nodejs.org/download/release/
But it says 'no such file or directory' when you try run node in shell. It needs to be built with android NDK.

My chipset is armv8 64bit but unfortunately the rom is 32bit, so I cant use the provided node 14 armv64 from the firebase link.

The dev said in #21 that they no longer support 32bit for future node versions.

Instructions for building node:
https://github.com/sjitech/build-nodejs-for-android

**Comment by rajeshisgood** [comment]
I am also stuck on node v10

**Comment by sonolosoft** [comment]
Update Dorynode to latest Nodejs+NPM with Termux binaries
https://github.com/sonolosoft/guide/blob/main/dorynode/update.md

**Comment by rajeshisgood** [comment]
Did you tried to use android ndk ?

**Comment by sonolosoft** [comment]
Sorry no access to pc. x86 emulator crashes won't boot.

**Comment by ivere27** [comment]
I don't have plan to support non LTS || 32bit || x86 version.

please try the brand new one. arm64 v16.15.1
https://dorynode.firebaseapp.com/v16.15.1_arm64_release/node

**Comment by rajeshisgood** [comment]
@ivere27 , at least post a video on youtube about how to compile by yourself.

**Comment by ivere27** [comment]
@rajeshisgood sorry i dont have time to youtube..

v16 LTS arm64 version is under review in the google play.
please use with an arm64 device later.
