### ISSUE TITLE
Request another option to update node version

### ISSUE THREAD

**Issue by aharon-k** [tempage/dorynode#28]
Hi. 1, Thank you for the excellent and unique app. 2, Is it possible to update a node version from a file inside the computer? I have blocked access to https://dorynode.firebaseapp.com/v10.15.1_arm_release/node If yes, how can I get the file from another server? Maybe drive, Maybe on github. Maybe in The terminal. Thank you so much for that

**Comment by digimbyte** [comment]
This repo is most likely stored on Google Firebase cloud storage solution, you could use the v14.16.0 version available

**Comment by sonolosoft** [comment]
Run a tiny localhost html server on your phone, put the node binary inside its www folder, go into dory > download file, point it to the node binary on your localhost server.

**Comment by ivere27** [comment]
just copy the node binary  https://dorynode.firebaseapp.com/v10.15.1_arm_release/node to your server.
then, you can use 'curl' or 'scp' or 'git' in the shell. I have ported them into dorynode/files/bin/

https://github.com/tempage/dorynode/issues/34#issuecomment-1171347244
