### ISSUE TITLE
cb.apply is not a function node v14

### ISSUE THREAD

**Issue by digimbyte** [tempage/dorynode#30]
I bought a second hand lenovo yoga book with hopes of using it to code on the go.
I have setup dory node with v14.16.0
The device is an Intel CPU Android 6.1  i686 
I need to install some cli tools but it's reporting that cb.apply is not a function, doing some research, this maybe tied to a dependency that was retired after v12.11

Happy to help debug.

**Comment by ivere27** [comment]
sorry, dorynode do not support x86 cpu anymore. please use old version.
https://github.com/tempage/dorynode/blob/master/42.apk
