### ISSUE TITLE
Serious Newbie Question - Sorry. How To Do "npm install ewelink-api"?

### ISSUE THREAD

**Issue by whitedavidp** [tempage/dorynode#32]
I am trying to use the ewelink api on my Android. The api is documented here <https://ewelink-api.vercel.app/docs/introduction>. And the 1st thing I have to do is the npm install.

How/where do I accomplish this?

Thanks

**Comment by whitedavidp** [comment]
Made some progress by executing a shell. Sorry.

**Comment by ivere27** [comment]
Sorry for the late reply. good luck!! 👍
