### ISSUE TITLE
Error trying to npm install... 

### ISSUE THREAD

**Issue by whitedavidp** [tempage/dorynode#33]
![Screenshot_2022-04-11-12-51-09](https://user-images.githubusercontent.com/12023355/162826301-79d33e6f-6a9e-4c6d-aa42-37a26d19c4c6.png)

No real idea why this should happen. Any suggestions?

Thanks

**Comment by ivere27** [comment]
create your own public/private keys in the shell.

$ ssh-keygen  
enter + enter...
and check the key files exist

$ cd  ~/.ssh
$ ls
id_rsa id_rsa.pub
