### ISSUE TITLE
Cant upgrade nodejs

### ISSUE THREAD

**Issue by CALEB789** [tempage/dorynode#34]
I have been struggling with upgrading node. It keeps loading and it never turns off
![Screenshot_20220613-194759_dnodejs](https://user-images.githubusercontent.com/58883113/173404566-803f667c-3f5b-4a93-8157-bed8aca4b71b.jpg)

**Comment by ivere27** [comment]
well, the link https://dorynode.firebaseapp.com/v14.16.0_arm64_release/node is wokring.
make sure the node process is killed.

or you can replace with the new one by curl command in the shell.

$ killall node
$ cd ../files/bin
$ rm -rf node
$ curl https://dorynode.firebaseapp.com/v14.16.0_arm64_release/node -o node
$ chmod a+x node

that's all. good luck
