### ISSUE TITLE
require() not working in Node.js v14

### ISSUE THREAD

**Issue by Alluseri** [tempage/dorynode#35]
```js
console.log(1);
const fetch = require("node-fetch");
console.log(2);
```
After 1 in STDOUT, the process finishes with error code 1, no additional debug log given. The module is definitely installed.

**Comment by ivere27** [comment]
sorry for the late update.
be a beta tester at https://play.google.com/store/apps/details?id=io.tempage.dorynode
and reinstall dorynode.

Node v16.15.1
npm 6.14.17
arm64 (node, ssh, ssl, curl, git) / API 23

If it works, I'll put it into production.

**Comment by ivere27** [comment]
you can download the latest dorynode version in google play.
it will work.

**Comment by Alluseri** [comment]
Thank you.
