### ISSUE TITLE
Can't install npm package after upgrade

### ISSUE THREAD

**Issue by HenryProject** [tempage/dorynode#36]
Thanks for your hard work, after I upgraded the provided node js version in Google Play Store. When I try to install new npm packages I get the following error:

```
npm ERR! Linux 4.9.112-perf-gd3c5b23
npm ERR! argv "/data/data/io.tempage.dorynode/files/bin/node" "/data/user/0/io.tempage.dorynode/files/npm/bin/npm-cli.js" "install" "-g" "piconvert"
npm ERR! node v14.16.0
npm ERR! npm  v3.10.10

npm ERR! cb.apply is not a function
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /data/data/io.tempage.dorynode/cache/npm-debug.log
code : 1 / signal : 0

```

I've searched for the log file but I didn't find it.

**Comment by ivere27** [comment]
Oh, I'll update the dorynode with the lastest LTS version in a week.

**Comment by ivere27** [comment]
sorry for the late update.
be a beta tester at https://play.google.com/store/apps/details?id=io.tempage.dorynode
and reinstall dorynode.

Node v16.15.1
npm 6.14.17
arm64 (node, ssh, ssl, curl, git) / API 23

If it works, I'll put it into production.

**Comment by intenceTech** [comment]
I downloaded the beta tester but when I want to install new npm packages there is a new error

`WARNING: linker: /data/data/io.tempage.dorynode/files/usr/lib/lib_node.so: unsupported flags DT_FLAGS_1=0x8000001
code : 1 / signal : 0`

**Comment by ivere27** [comment]
@intenceTech  could you provide your device information? device model, arch, os etcs

**Comment by intenceTech** [comment]
The device is Sunmi T2, android version : 7.1.1, os version : 3.4.9

**Comment by ivere27** [comment]
is it just a warning or an error?
I have updated a new beta version, please try it.

**Comment by HenryProject** [comment]
Wow! Many thanks for the update, everything works like charm. That was awesome. Now I can easily write npm modules with my phone via Dory.

**Comment by intenceTech** [comment]
> is it just a warning or an error? I have updated a new beta version, please try it.

Hello, it's just a warning but my program does not want to launch I use npm libraries (express, net, cors)

**Comment by ivere27** [comment]
@intenceTech please, uninstall and install the dorynode app again.
