### ISSUE TITLE
Getting Error EACCES

### ISSUE THREAD

**Issue by bhanuagarwal73** [tempage/dorynode#37]
npm ERR! code EACCES
npm ERR! syscall open
npm ERR! path /storage/emulated/0/Channels/package-lock.json
npm ERR! errno -13
npm ERR! Error: EACCES: permission denied, open '/storage/emulated/0/Channels/package-lock.json'
npm ERR!  [OperationalError: EACCES: permission denied, open '/storage/emulated/0/Channels/package-lock.json'] {
npm ERR!   cause: [Error: EACCES: permission denied, open '/storage/emulated/0/Channels/package-lock.json'] {
npm ERR!     errno: -13,
npm ERR!     code: 'EACCES',
npm ERR!     syscall: 'open',
npm ERR!     path: '/storage/emulated/0/Channels/package-lock.json'
npm ERR!   },
npm ERR!   isOperational: true,
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'open',
npm ERR!   path: '/storage/emulated/0/Channels/package-lock.json'
npm ERR! }
npm ERR! 
npm ERR! The operation was rejected by your operating system.
npm ERR! It is likely you do not have the permissions to access this file as the current user
npm ERR! 
npm ERR! If you believe this might be a permissions issue, please double-check the
npm ERR! permissions of the file and its containing directories, or try running
npm ERR! the command again as root/Administrator.

npm ERR! A complete log of this run can be found in:
npm ERR!     /data/data/io.tempage.dorynode/app_HOME/.npm/_logs/2022-07-16T23_10_43_095Z-debug.log
code : 243 / signal : 0

**Comment by bhanuagarwal73** [comment]
It was working well 3 days back but now got this issue.
In addition when loading the directory containing package.json then its not showing any package.json file data there

**Comment by bhanuagarwal73** [comment]
Resolved the above issue but now getting below:
![Screenshot_20220717-174310_dnodejs](https://user-images.githubusercontent.com/38572421/179397794-b5559e0d-bf27-4623-bc68-0d01697af171.jpg)

**Comment by ivere27** [comment]
how can i re-produce the error? 
please give me some instruction.

**Comment by bhanuagarwal73** [comment]
Is there any way to clean the directory & reinstall everything?

I tried by doing it with rm -rf directory... but throwing error as permission denied

I am seeing issue with accessing typescript. Even though I declared & installed it at global level ../files/lib but throwing permission denied.

**Comment by ivere27** [comment]
well, the easiest way is just uninstall and install the dorynode app.

**Comment by bhanuagarwal73** [comment]
@ivere27 already did thrice but same issue. I can still see the directory /data/user/0/io.tempage.dorynode...

**Comment by bhanuagarwal73** [comment]
@ivere27 is there any way to define the custom path for dory node?
Like installing all the dependencies in read write folders (means all the dory nodes dependencies not project level dependencies)?

Actually the issue is its unable to read the typescript dependencies (it was working 5 days back)

**Comment by bhanuagarwal73** [comment]
![Screenshot_20220719-205629_dnodejs](https://user-images.githubusercontent.com/38572421/179789108-96323377-30da-436a-bd37-f3b1319501f8.jpg)

**Comment by ivere27** [comment]
'running a binary in the files path' is not allowed anymore. due to the android policy.
https://developer.android.com/about/versions/10/behavior-changes-10#execute-permission

so, use tsc like this ```$ node `wihch tsc` ```

```
:/data/data/io.tempage.dorynode/app_HOME $ npm install -g typescript
...
:/data/data/io.tempage.dorynode/app_HOME $ which tsc
/data/user/0/io.tempage.dorynode/files/bin/tsc
:/data/data/io.tempage.dorynode/app_HOME $ node /data/user/0/io.tempage.dorynode/files/bin/tsc
```

**Comment by bhanuagarwal73** [comment]
@ivere27 still same issue


> zee@1.0.0 start /storage/emulated/0/Channels Sonyliv
> /data/user/0/io.tempage.dorynode/files/bin/tsc && node out/index.js

sh: /data/user/0/io.tempage.dorynode/files/bin/tsc: Permission denied
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! zee@1.0.0 start: `/data/user/0/io.tempage.dorynode/files/bin/tsc && node out/index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the zee@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /data/data/io.tempage.dorynode/app_HOME/.npm/_logs/2022-07-21T19_52_26_195Z-debug.log
code : 1 / signal : 0
![Uploading Screenshot_20220722-012455_dnodejs.jpg…]()

**Comment by bhanuagarwal73** [comment]
Finally it worked. Seems issue with node too.

after I gave complete path for node & tsc it worked. 
node path- /data/user/0...../files/bin/node
tsc path- /data/user/0...../files/bin/tsc


Is there any way to create shortcut for this? like I can give node_path = /data/user/0...../files/bin/node & tsc_path=/data/user/0...../files/bin/node
and I can use this in script section as 
"Script": {
    "start": "node_path tsc_path && node_path out/index.js

**Comment by ivere27** [comment]
glad to hear that.
by the way, you can use 'alias' in the shell.
