### ISSUE TITLE
dory nodejs's new version doesn't show syntax error and any other errors explicitly.

### ISSUE THREAD

**Issue by fahimShahriaar** [tempage/dorynode#39]
dory nodejs's new version doesn't show syntax error and any other errors explicitly. When syntax error occurs it logs "pid 17582 exited with code : 1 / signal : 0" Also it does not tell in which line the error occurs

**Comment by ivere27** [comment]
thanks for the report, I'll fix it.

**Comment by fahimShahriaar** [comment]
Thanks for your response. I want to mention again it doesn't show any error explicitly (ex: **module not found**, syntax error and others). Most important thing is to log the error **Line Number**

**Comment by ivere27** [comment]
please update the dory node to latest version. it shows the error.
