### ISSUE TITLE
Async function not working

### ISSUE THREAD

**Issue by Suzannekerr** [tempage/dorynode#4]
I am trying to run a simple p2p node on my android use your app but I get the following error:
async start(){
      ^^^^^

SyntaxError: Unexpected identifier
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/storage/emulated/0/Tokyo/p2pnode/p2pnode-test.js:1:77

**Comment by legouju** [comment]
same 

autho it errors on async path not start for me

after some googling, i arrived here:
https://github.com/tapio/live-server/issues/305

looks like open doesnt support the latest version of node or you need to update node
autho following their solution still didnt fix

:/

**Comment by kahurangitama** [comment]
Same for me. Any chance to update the node to 10+ version?

**Comment by Alchemist7534** [comment]
Please do something about this

**Comment by Alchemist7534** [comment]
Found a solution, all you need to do is update the nodejs version and it's quite straightforward
Follow the instructions below:

1.  Open the Dory nodejs app
2. click on the right top menu bar
3.  Click on "download file"
4.  Paste  "https://dorynode.firebaseapp.com/v8.3.0_arm_release/node" in the URL input field (without the quotes of course)
5. check the "appfiles" radio box
6. check the "executable" check box
7. Click OK and wait for the download to complete
8. Cheers, be happy and continue your work
p.s: To the developers, nice app I love it

- [ Alchemist]

**Comment by Soumil1111** [comment]
> Found a solution, all you need to do is update the nodejs version and it's quite straightforward
> Follow the instructions below:
> 
> 1. Open the Dory nodejs app
> 2. click on the right top menu bar
> 3. Click on "download file"
> 4. Paste  "https://dorynode.firebaseapp.com/v8.3.0_arm_release/node" in the URL input field (without the quotes of course)
> 5. check the "appfiles" radio box
> 6. check the "executable" check box
> 7. Click OK and wait for the download to complete
> 8. Cheers, be happy and continue your work
>    p.s: To the developers, nice app I love it
> 
> * [ Alchemist]

Nice

**Comment by abiriadev** [comment]
> Found a solution, all you need to do is update the nodejs version and it's quite straightforward
> Follow the instructions below:
> 
> 1. Open the Dory nodejs app
> 2. click on the right top menu bar
> 3. Click on "download file"
> 4. Paste  "https://dorynode.firebaseapp.com/v8.3.0_arm_release/node" in the URL input field (without the quotes of course)
> 5. check the "appfiles" radio box
> 6. check the "executable" check box
> 7. Click OK and wait for the download to complete
> 8. Cheers, be happy and continue your work
>    p.s: To the developers, nice app I love it
> 
> * [ Alchemist]

Is there any way to use this solution offline?

**Comment by ivere27** [comment]
thanks for the instructions.
