### ISSUE TITLE
protocol not found: npm install npm@latest -g

### ISSUE THREAD

**Issue by laserblue** [tempage/dorynode#6]
I keep getting "can't find module" and when I try updating after checking app files and executable, I just get "protocol not found: npm install npm@latest -g"

Url: npm install npm@latest -g
pathname: /data/user/0/io.tempage.dorynode/files/bin/
filename: npm install npm@latest -g

**Comment by ivere27** [comment]
dorynode does not support 'update npm by itself'

please use the latest dorynode.
